service: auth-server

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    shouldStartNameWithService: true
  region: ca-central-1
  timeout: 60
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    PROJECT_ID: ${file(config.json):PROJECT_ID}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:cd 
      - http:
          path: api/get-auth-url
          method: get
          
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
         
  getCalandarEvents:
    handler: handler.getCalandarEvents
    events:
      - http:
          path: api/get-events/{access_token}/{max_results}
          method: get
